-- Incident Analysis V2: Add new fields for redesigned 2-page form

ALTER TABLE ehs_incident_analysis
  ADD COLUMN IF NOT EXISTS incident_type TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS time TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS activity_type TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS pre_incident_activity TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS failure_type TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS how_stopped TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS controls_failed JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS sop_deviation BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS authorization_competence BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS pressure_constraints JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS historical_incident_date DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS past_incidents_text TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS impact_description TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS worst_case_potential TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS immediate_actions TEXT DEFAULT NULL;
